version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: grocery_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  grocery-application:
    build: .
    ports:
      - "9090:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/grocery_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root_password
volumes:
  mysql_data:

